#include "jdprotocol.h"
#include "jdservices.h"
#include <string.h>
#include <stdio.h>

#define DEVICE_NAME "JACDAC Button v1.0"
#define NUM_CAPTOUCH_CH 2

void jd_add_ad_data(const char *name, uint32_t class, uint8_t flags, const void *src,
                    uint32_t size);

const static jd_captouch_advertisement_data_t captouchAd[] = { 0x00, NUM_CAPTOUCH_CH };

void jd_add_services() {
    jd_add_ad_data("Captouch Driver", JD_SERVICE_CLASS_CAPTOUCH, 0, &captouchAd,
                   sizeof(captouchAd));
}

void print_bytes(const void *src, uint32_t size) {
    for (int i = 0; i < size; ++i) {
        printf(" 0x%02x,", ((uint8_t *)src)[i]);
        if (i % 16 == 15)
            printf("\n");
    }
}

void jd_add_ad_data(const char *name, uint32_t class, uint8_t flags, const void *src,
                    uint32_t size) {
    printf("// Service %s (class=0x%08x, flags=0x%02x)\n", name, class, flags);
    print_bytes(&class, 4);
    print_bytes(&flags, 1);
    print_bytes(src, size);
    printf("\n");
}

void jd_fill_ad_data() {
    printf("// Device name: \"%s\"\n", DEVICE_NAME);
    uint8_t flags = JD_DEVICE_FLAGS_HAS_NAME;
    print_bytes(&flags, 1);
    int len = strlen(DEVICE_NAME);
    print_bytes(&len, 1);
    print_bytes(DEVICE_NAME, len);
    printf("\n");
    jd_add_services();
}

int main() {
    printf("// Generated by genad.c\n");
    printf("const static uint8_t adData[] = {\n");
    jd_fill_ad_data();
    printf("};\n");
    printf("// End of generated code\n");
    return 0;
}
